# Generated by Django 4.2 on 2024-03-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artists', models.JSONField()),
                ('genres', models.JSONField()),
                ('cover', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
