# Generated by Django 4.2 on 2024-04-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0002_alter_playlist_artists_alter_playlist_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='artists',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='genres',
            field=models.CharField(max_length=255),
        ),
    ]
