# Generated by Django 4.2 on 2024-04-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0003_alter_playlist_artists_alter_playlist_genres'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='artists',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='genres',
        ),
        migrations.AddField(
            model_name='playlist',
            name='artists',
            field=models.ManyToManyField(to='playlist_app.artist'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='genres',
            field=models.ManyToManyField(to='playlist_app.genre'),
        ),
    ]
