# Generated by Django 4.2 on 2024-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0005_alter_playlist_artists_alter_playlist_cover_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default=None, upload_to='static/uploads/'),
            preserve_default=False,
        ),
    ]
