# Generated by Django 4.2 on 2024-04-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0008_alter_playlist_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='playlist_default.png', upload_to=''),
        ),
    ]
