# Generated by Django 4.2 on 2024-04-26 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_app', '0011_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
